import Link from 'next/link';
import './globals.css';

export const metadata = {
  title: 'Next Study',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
  const response = await fetch(
    'http://localhost:9999/topics',
    // {next: { revalidate: 0 } }, // 0인 경우 캐시를 쓰지 않겠다
    { cache: 'no-store' }, // 캐시 정책을 사용하지 않겠다.
  );
  const topics = await response.json();

  return (
    <html>
      <body>
        <h1>
          <Link href="/">WEB</Link>
        </h1>
        <ol>
          {topics.map((topic) => (
            <li key={topic.id}>
              <Link href={`/read/${topic.id}`}>{topic.title}</Link>
            </li>
          ))}
        </ol>
        {children}
        <ul>
          <li>
            <Link href="/create">Create</Link>
          </li>
          <li>
            <Link href="/update/1">Update</Link>
          </li>
          <li>
            <input type="button" value="delete" />
          </li>
        </ul>
      </body>
    </html>
  );
}
